image:
    file: .gitpod.Dockerfile

tasks:
    - name: Install nextflow
      init: |
          apt install sudo
          cd ~
          wget -qO- https://get.nextflow.io | bash
          sudo cp nextflow /usr/local/bin
      command: bash